spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_NAME}/${MYSQL_DATABASE}?characterEncoding=utf-8&useSSL=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  http:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB

server:
  context-path: ${SERVER_CONTEXT_PATH}

flyway:
  enabled: true
  validate-on-migrate: false

transcode:
  formats:
    browse:
      format: mp4
      video-codec: libx264
      bitrate: 640000
  threads: 5

storage:
  base-path: ${STORAGE_BASE_PATH}
  base-url: ${STORAGE_BASE_URL}

script:
  base-path: /

task:
  output-path: /tmp
  threads: 10

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/video_ocr?characterEncoding=utf-8
    username: root
    password: password

server:
  context-path: /ocr-server

storage:
  base-path: /Users/mengli/Temp/docker-test-web/
  base-url: http://localhost:9003/

script:
  base-path: /Users/mengli/Work/MyProjects/video_ocr/ocr-server/src/main/scripts/

task:
  output-path: /Users/mengli/Temp/docker-test-web/

---
spring:
  profiles: aliyun
  datasource:
    url: jdbc:mysql://localhost/video_ocr?characterEncoding=utf-8&useSSL=false
    username: root
    password: Dream0628!

storage:
  base-path: /usr/local/nginx/html/
  base-url: http://www.xiaoheifamily.com/

script:
  base-path: /usr/local/video-ocr/scripts/

task:
  output-path: /tmp/ocr-task/
---
spring:
  profiles: aliyun-lingpan
  datasource:
    url: jdbc:mysql://localhost/video_ocr?characterEncoding=utf-8&useSSL=false
    username: root
    password: cdvcloud

storage:
  base-path: /usr/local/nginx/html/
  base-url: http://101.200.228.240/

script:
  base-path: /usr/local/video-ocr/scripts/

task:
  output-path: /tmp/ocr-task/