spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_NAME}/${MYSQL_DATABASE}?characterEncoding=utf-8&useSSL=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  http:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB

server:
  context-path: ${SERVER_CONTEXT_PATH}

flyway:
  enabled: true
  validate-on-migrate: false

feign:
  hystrix:
    enabled: true

hystrix:
  command.default.execution.timeout.enabled: false
  threadpool.default.maxQueueSize: 2147483647
  threadpool.default.queueSizeRejectionThreshold: 2147483647

transcode:
  formats:
    browse:
      format: mp4
      video-codec: libx264
      bitrate: 640000
  threads: 5

storage:
  base-path: ${STORAGE_BASE_PATH}
  base-url: ${STORAGE_BASE_URL}

script:
  base-path: /

task:
  output-path: /tmp
  baidu-ocr-async: ${BAIDU_OCR_ASYNC:false}
  ocr-delay-millis: ${OCR_DELAY_MILLIS:10}

baidu:
  ocr:
    base-url: ${BAIDU_OCR_BASE_URL:http://180.76.111.230:8120}}
    url: ${BAIDU_OCR_URL:/GeneralClassifyService/classify}

activation:
  code-path: /activation/activation_code
