version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306"
    networks:
      - video-ocr-network
    volumes:
      - "/var/video-ocr/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  server:
    image: registry.cn-beijing.aliyuncs.com/dreamcoder/video-ocr-server
    ports:
      - "8080"
    networks:
      - video-ocr-network
    volumes:
      - "/var/video-ocr/storage:/storage"
    environment:
      SERVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH}
      MYSQL_HOST_NAME: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      STORAGE_BASE_PATH: /storage
      STORAGE_BASE_URL: http://${HOST_NAME}:${HOST_PORT}/storage
    depends_on:
      - db
  web:
    image: registry.cn-beijing.aliyuncs.com/dreamcoder/video-ocr-web
    ports:
      - "${HOST_PORT}:80"
    networks:
      - video-ocr-network
    volumes:
      - "/var/video-ocr/storage:/usr/share/nginx/html/storage"
    depends_on:
      - server

networks:
  video-ocr-network:
