version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306"
    networks:
      - video-ocr-network
    volumes:
      - "${HOST_VOLUME}/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    deploy:
      resources:
        limits:
          memory: 200M
  server:
    image: registry.cn-beijing.aliyuncs.com/mengli/video-ocr-server_tesseract-ocr
    ports:
      - "8080"
    networks:
      - video-ocr-network
    mac_address: ${HOST_MAC_ADDRESS}
    volumes:
      - "${HOST_VOLUME}/storage:/storage"
      - "${HOST_VOLUME}/activation:/activation"
    environment:
      SERVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH}
      MYSQL_HOST_NAME: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      STORAGE_BASE_PATH: /storage
      STORAGE_BASE_URL: http://${HOST_NAME}:${HOST_PORT}/storage
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2000M
    depends_on:
      - db
  web:
    image: registry.cn-beijing.aliyuncs.com/mengli/video-ocr-web_tesseract-ocr
    ports:
      - "${HOST_PORT}:80"
    networks:
      - video-ocr-network
    volumes:
      - "${HOST_VOLUME}/storage:/usr/share/nginx/html/storage"
    deploy:
      resources:
        limits:
          memory: 200M    
    depends_on:
      - server

networks:
  video-ocr-network:
